[package]
name = "miniparse-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "miniparse"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
miniparse-lib = { path = "../miniparse-lib" }
